before:
  hooks:
    - make install
    - make web/build
builds:
  - main: main.go
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
archives:
  - replacements:
      darwin: Darwin
      amd64: x86_64
    files:
      - assets
      - README.md
      - config.sample.yaml
checksum:
  name_template: 'checksums.txt'
release:
  prerelease: auto
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch

brews:
  -
    # GitHub/GitLab repository to push the formula to
    tap:
      owner: sawadashota
      name: homebrew-tap

    url_template: https://github.com/sawadashota/unifi-doorbell-chime/releases/download/{{ .Tag }}/{{ .ArtifactName }}
    commit_author:
      name: "Shota Sawada"
      email: shota@sslife.tech

    homepage: "https://github.com/sawadashota/unifi-doorbell-chime"
    description: "Notify to Mac when Doorbell rung."
    skip_upload: false
    install: |
      bin.install "unifi-doorbell-chime"
      Dir.mkdir(Dir.home + '/.unifi-doorbell-chime')

      require 'fileutils'
      FileUtils.cp('config.sample.yaml', Dir.home + '/.unifi-doorbell-chime/config.yaml')
      FileUtils.cp_r('assets', Dir.home + '/.unifi-doorbell-chime/assets')
