on:
  push:
    branches:
      - main

name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        with:
          release-type: simple
          default-branch: main
          bump-minor-pre-major: yes
          token: ${{ secret._GITHUB_TOKEN }}
